// <auto-generated />
using System;
using Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.DataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726180051_RebaseRenamedEntities")]
    partial class RebaseRenamedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateClose");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("double")
                        .HasColumnName("TradeOpen");

                    b.Property<double?>("ExitPrice")
                        .HasColumnType("double")
                        .HasColumnName("TradeClose");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("TradeCodeId");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateOpen");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Count");

                    b.Property<int>("Signal")
                        .HasColumnType("int")
                        .HasColumnName("TradeSignal");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<int>("TradeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TradeTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Trades", t =>
                        {
                            t.HasCheckConstraint("CK_Trade_PositiveCount", "`Count` > 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.TradeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TradeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stock"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Futures"
                        });
                });

            modelBuilder.Entity("Domain.Instruments.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ExchangeId");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("TradeCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gazprom",
                            Symbol = "GAZP"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nornickel",
                            Symbol = "GMKN"
                        });
                });

            modelBuilder.Entity("Domain.Instruments.Entities.UserInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("TradeCodeId");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("UserId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("UserTradeCode", (string)null);
                });

            modelBuilder.Entity("Domain.Notes.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("TradeCodeId");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("int")
                        .HasColumnName("TradeStrategyId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NoteText");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "InstrumentId")
                        .IsUnique();

                    b.HasIndex("UserId", "StrategyId")
                        .IsUnique();

                    b.ToTable("Notes", t =>
                        {
                            t.HasCheckConstraint("CK_Note_ExclusiveTarget", "(`TradeCodeId` IS NOT NULL AND `TradeStrategyId` IS NULL) OR (`TradeCodeId` IS NULL AND `TradeStrategyId` IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.Reminders.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("TradeCodeId");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateTime");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TextRemind");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeReminds", (string)null);
                });

            modelBuilder.Entity("Domain.Strategies.Entities.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accuracy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("InvestmentHorizon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LimitationsDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("LimitDesc");

                    b.Property<string>("LogicDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("LogicDesc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SignalFrequency")
                        .HasColumnType("longtext");

                    b.Property<string>("UsageDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("UseDesc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TradeStrategies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 81,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic trend-following strategy for an asset. Minimal risk, rare signals.",
                            InvestmentHorizon = "1-3 weeks",
                            IsActive = true,
                            LimitationsDescription = "Strategy exclusively for following the trend",
                            LogicDescription = "Analysis of a long-term chart to confirm movement",
                            Name = "TrendFollowingStrategy",
                            SignalFrequency = "1-2 times a month",
                            UsageDescription = "Follow the main trend, during low or medium volatility"
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 99,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test strategy. 100000% profit per nanosecond",
                            InvestmentHorizon = "up to 1 week",
                            IsActive = true,
                            LimitationsDescription = "SuperStart",
                            LogicDescription = "Very clear",
                            Name = "Test",
                            SignalFrequency = "3 times a month",
                            UsageDescription = "Use it however you like"
                        });
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int")
                        .HasColumnName("TradeStrategyId");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserId", "StrategyId")
                        .IsUnique();

                    b.ToTable("UserTradeStrategies", (string)null);
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserStrategyInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("TradeCodeId");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserId", "InstrumentId", "StrategyId")
                        .IsUnique();

                    b.HasIndex("UserId", "StrategyId", "InstrumentId");

                    b.ToTable("UserStrategyTradeCodes", (string)null);
                });

            modelBuilder.Entity("Domain.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastLoginDate");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("HashPassword");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RegisterDate");

                    b.Property<string>("TelegramId")
                        .HasColumnType("longtext")
                        .HasColumnName("TgId");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Trade", b =>
                {
                    b.HasOne("Domain.Instruments.Entities.Instrument", "Instrument")
                        .WithMany("Trades")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TradeType", "TradeType")
                        .WithMany("Trades")
                        .HasForeignKey("TradeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany("Trades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("TradeType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Instruments.Entities.UserInstrument", b =>
                {
                    b.HasOne("Domain.Instruments.Entities.Instrument", "Instrument")
                        .WithMany("UserInstruments")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Notes.Entities.Note", b =>
                {
                    b.HasOne("Domain.Instruments.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId");

                    b.HasOne("Domain.Strategies.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId");

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Strategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Reminders.Entities.Reminder", b =>
                {
                    b.HasOne("Domain.Instruments.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserStrategy", b =>
                {
                    b.HasOne("Domain.Strategies.Entities.Strategy", "Strategy")
                        .WithMany("UserStrategies")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany("UserStrategies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserStrategyInstrument", b =>
                {
                    b.HasOne("Domain.Instruments.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Strategies.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Strategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TradeType", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Domain.Instruments.Entities.Instrument", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserInstruments");
                });

            modelBuilder.Entity("Domain.Strategies.Entities.Strategy", b =>
                {
                    b.Navigation("UserStrategies");
                });

            modelBuilder.Entity("Domain.Users.Entities.User", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserStrategies");
                });
#pragma warning restore 612, 618
        }
    }
}
