// <auto-generated />
using System;
using Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721053405_delNetIncome")]
    partial class delNetIncome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("TradeClose")
                        .HasColumnType("double");

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<double>("TradeOpen")
                        .HasColumnType("double");

                    b.Property<int>("TradeSignal")
                        .HasColumnType("int");

                    b.Property<int>("TradeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("TradeTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Domain.Entities.TradeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TradeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stock"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Futures"
                        });
                });

            modelBuilder.Entity("Domain.Notes.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<int?>("TradeStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("TradeStrategyId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes", t =>
                        {
                            t.HasCheckConstraint("CK_Note_ExclusiveTarget", "(`TradeCodeId` IS NOT NULL AND `TradeStrategyId` IS NULL) OR (`TradeCodeId` IS NULL AND `TradeStrategyId` IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.Reminders.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TextRemind");

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeReminds", (string)null);
                });

            modelBuilder.Entity("Domain.Strategies.Entities.TradeStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accuracy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("InvestmentHorizon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LimitDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("LogicDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SignalFrequency")
                        .HasColumnType("longtext");

                    b.Property<string>("UseDesc")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TradeStrategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 81,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic trend-following strategy for an asset. Minimal risk, rare signals.",
                            InvestmentHorizon = "1-3 weeks",
                            IsActive = true,
                            LimitDesc = "Strategy exclusively for following the trend",
                            LogicDesc = "Analysis of a long-term chart to confirm movement",
                            Name = "TrendFollowingStrategy",
                            SignalFrequency = "1-2 times a month",
                            UseDesc = "Follow the main trend, during low or medium volatility"
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 99,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test strategy. 100000% profit per nanosecond",
                            InvestmentHorizon = "up to 1 week",
                            IsActive = true,
                            LimitDesc = "SuperStart",
                            LogicDesc = "Very clear",
                            Name = "Test",
                            SignalFrequency = "3 times a month",
                            UseDesc = "Use it however you like"
                        });
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserStrategyTradeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<int?>("TradeStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("TradeStrategyId");

                    b.HasIndex("UserId", "TradeCodeId", "StrategyId")
                        .IsUnique();

                    b.ToTable("UserStrategyTradeCodes");
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserTradeStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TradeStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeStrategyId");

                    b.HasIndex("UserId", "TradeStrategyId")
                        .IsUnique();

                    b.ToTable("UserTradeStrategies");
                });

            modelBuilder.Entity("Domain.TradeCodes.Entities.TradeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId")
                        .IsUnique();

                    b.ToTable("TradeCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gazprom",
                            ExchangeId = "GAZP"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nornickel",
                            ExchangeId = "GMKN"
                        });
                });

            modelBuilder.Entity("Domain.TradeCodes.Entities.UserTradeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("UserId", "TradeCodeId")
                        .IsUnique();

                    b.ToTable("UserTradeCode");
                });

            modelBuilder.Entity("Domain.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TelegramId")
                        .HasColumnType("longtext")
                        .HasColumnName("TgId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Trade", b =>
                {
                    b.HasOne("Domain.TradeCodes.Entities.TradeCode", "TradeCode")
                        .WithMany("Trades")
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TradeType", "TradeType")
                        .WithMany("Trades")
                        .HasForeignKey("TradeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany("Trades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("TradeType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Notes.Entities.Note", b =>
                {
                    b.HasOne("Domain.TradeCodes.Entities.TradeCode", "TradeCode")
                        .WithMany()
                        .HasForeignKey("TradeCodeId");

                    b.HasOne("Domain.Strategies.Entities.TradeStrategy", "TradeStrategy")
                        .WithMany()
                        .HasForeignKey("TradeStrategyId");

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("TradeStrategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Reminders.Entities.Reminder", b =>
                {
                    b.HasOne("Domain.TradeCodes.Entities.TradeCode", "TradeCode")
                        .WithMany()
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserStrategyTradeCode", b =>
                {
                    b.HasOne("Domain.TradeCodes.Entities.TradeCode", "TradeCode")
                        .WithMany()
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Strategies.Entities.TradeStrategy", "TradeStrategy")
                        .WithMany()
                        .HasForeignKey("TradeStrategyId");

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("TradeStrategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Strategies.Entities.UserTradeStrategy", b =>
                {
                    b.HasOne("Domain.Strategies.Entities.TradeStrategy", "TradeStrategy")
                        .WithMany("UserTradeStrategies")
                        .HasForeignKey("TradeStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany("UserTradeStrategies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeStrategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.TradeCodes.Entities.UserTradeCode", b =>
                {
                    b.HasOne("Domain.TradeCodes.Entities.TradeCode", "TradeCode")
                        .WithMany("UserTradeCodes")
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TradeType", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Domain.Strategies.Entities.TradeStrategy", b =>
                {
                    b.Navigation("UserTradeStrategies");
                });

            modelBuilder.Entity("Domain.TradeCodes.Entities.TradeCode", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserTradeCodes");
                });

            modelBuilder.Entity("Domain.Users.Entities.User", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserTradeStrategies");
                });
#pragma warning restore 612, 618
        }
    }
}
