using ViaTrade.Domain.Entities;
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViaTrade.Infrastructure.DataBase;

#nullable disable

namespace ViaTrade.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506212626_IdFix")]
    partial class IdFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DataBase.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<int?>("TradeStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("TradeStrategyId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes", t =>
                        {
                            t.HasCheckConstraint("CK_Note_ExclusiveTarget", "(`TradeCodeId` IS NOT NULL AND `TradeStrategyId` IS NULL) OR (`TradeCodeId` IS NULL AND `TradeStrategyId` IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.DataBase.NoteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("NoteTypes");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("NetIncome")
                        .HasColumnType("double");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<double?>("TradeClose")
                        .HasColumnType("double");

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<double>("TradeOpen")
                        .HasColumnType("double");

                    b.Property<int>("TradeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("TradeTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.TradeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId")
                        .IsUnique();

                    b.ToTable("TradeCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Газпром",
                            ExchangeId = "GAZP"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Норникель",
                            ExchangeId = "GMKN"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DataBase.TradeStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accuracy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("InvestmentHorizon")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LimitDesc")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("LogicDesc")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SignalFrequency")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UseDesc")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TradeStrategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 81,
                            Description = "Базовая стратегия следования биржевому тренду инструмента. Минамальный риск, редкие сигналы.",
                            InvestmentHorizon = "1-3 недели",
                            LimitDesc = "Стратегия исключительно для слелования тренду",
                            LogicDesc = "Анализ длительного времение гшрафика для подтвержеденгия движдениея",
                            Name = "TrendFollowingStrategy",
                            SignalFrequency = "1-2 раза в месяц",
                            UseDesc = "Следовать основному тренду, при низкой или средней валотильности"
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 99,
                            Description = "Тестовая стратегия. 100000% прибыли в наносекунду",
                            InvestmentHorizon = "до 1 недели",
                            LimitDesc = "СуперСтарта",
                            LogicDesc = "Ващё чётко",
                            Name = "Test",
                            SignalFrequency = "3 раза в месяц",
                            UseDesc = "Как по кайфу так и используй"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DataBase.TradeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TradeTypes");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TgId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.UserStrategyTradeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<int?>("TradeStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("TradeStrategyId");

                    b.HasIndex("UserId", "TradeCodeId", "StrategyId")
                        .IsUnique();

                    b.ToTable("UserStrategyTradeCodes");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.UserTradeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.HasIndex("UserId", "TradeCodeId")
                        .IsUnique();

                    b.ToTable("UserTradeCode");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.UserTradeStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TradeStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeStrategyId");

                    b.HasIndex("UserId", "TradeStrategyId")
                        .IsUnique();

                    b.ToTable("UserTradeStrategies");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.Note", b =>
                {
                    b.HasOne("Domain.Entities.DataBase.TradeCode", "TradeCode")
                        .WithMany()
                        .HasForeignKey("TradeCodeId");

                    b.HasOne("Domain.Entities.DataBase.TradeStrategy", "TradeStrategy")
                        .WithMany()
                        .HasForeignKey("TradeStrategyId");

                    b.HasOne("Domain.Entities.DataBase.NoteType", "NoteType")
                        .WithMany("Notes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DataBase.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteType");

                    b.Navigation("TradeCode");

                    b.Navigation("TradeStrategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.Trade", b =>
                {
                    b.HasOne("Domain.Entities.DataBase.TradeCode", "TradeCode")
                        .WithMany("Trades")
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DataBase.TradeType", "TradeType")
                        .WithMany("Trades")
                        .HasForeignKey("TradeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DataBase.User", "User")
                        .WithMany("Trades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("TradeType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.UserStrategyTradeCode", b =>
                {
                    b.HasOne("Domain.Entities.DataBase.TradeCode", "TradeCode")
                        .WithMany()
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DataBase.TradeStrategy", "TradeStrategy")
                        .WithMany()
                        .HasForeignKey("TradeStrategyId");

                    b.HasOne("Domain.Entities.DataBase.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("TradeStrategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.UserTradeCode", b =>
                {
                    b.HasOne("Domain.Entities.DataBase.TradeCode", "TradeCode")
                        .WithMany("UserTradeCodes")
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DataBase.User", "User")
                        .WithMany("UserTradeCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.UserTradeStrategy", b =>
                {
                    b.HasOne("Domain.Entities.DataBase.TradeStrategy", "TradeStrategy")
                        .WithMany("UserTradeStrategies")
                        .HasForeignKey("TradeStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DataBase.User", "User")
                        .WithMany("UserTradeStrategies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeStrategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.NoteType", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.TradeCode", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserTradeCodes");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.TradeStrategy", b =>
                {
                    b.Navigation("UserTradeStrategies");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.TradeType", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Domain.Entities.DataBase.User", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserTradeCodes");

                    b.Navigation("UserTradeStrategies");
                });
#pragma warning restore 612, 618
        }
    }
}
