<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<RootNamespace>ViaTrade.Api</RootNamespace>
		<AssemblyName>ViaTrade.Api</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>5001262e-6237-421d-b09e-f4956f03d30c</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Authentication\**" />
		<Content Remove="Authentication\**" />
		<EmbeddedResource Remove="Authentication\**" />
		<None Remove="Authentication\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.Development.json">
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" PrivateAssets="all" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\Configuration\Configuration.csproj" />
	</ItemGroup>

	<ItemGroup>
		<SwaggerDocument Include="web" OutputPath="$(ProjectDir)..\swagger\swagger.yaml" />
		<SwaggerDocument Include="tgbot" OutputPath="$(ProjectDir)..\swagger\swagger-tgbot.yaml" />
		<SwaggerDocument Include="analyzer" OutputPath="$(ProjectDir)..\swagger\swagger-analyzer.yaml" />
	</ItemGroup>

	<Target Name="GenerateSwagger" AfterTargets="Build">
		<MakeDir Directories="$(ProjectDir)..\swagger\" />

		<Exec
			EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development"
			IgnoreExitCode="true"
			Command="dotnet tool run swagger tofile --yaml --output &quot;%(SwaggerDocument.OutputPath)&quot; --openapiversion 3.0 &quot;$(TargetPath)&quot; %(SwaggerDocument.Identity)"
			WorkingDirectory="$(ProjectDir)"
		/>
	</Target>
</Project>
