<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<RootNamespace>ViaTrade.Api</RootNamespace>
		<AssemblyName>ViaTrade.Api</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>5001262e-6237-421d-b09e-f4956f03d30c</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Authentication\**" />
		<Content Remove="Authentication\**" />
		<EmbeddedResource Remove="Authentication\**" />
		<None Remove="Authentication\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.Development.json">
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="7.2.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.20">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\Configuration\Configuration.csproj" />
	</ItemGroup>

	<Import Project="Build\GenerateOpenApi.targets" />
	<ItemGroup>
		<OpenApiDocument Include="web" OutputPath="$(ProjectDir)..\openapi\openapi.yaml" />
		<OpenApiDocument Include="tgbot" OutputPath="$(ProjectDir)..\openapi\openapi-tgbot.yaml" />
		<OpenApiDocument Include="analyzer" OutputPath="$(ProjectDir)..\openapi\openapi-analyzer.yaml" />
	</ItemGroup>
</Project>
